# -*- coding: utf-8 -*-
"""Yi_Liu (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/163M26LbcCKU0xA46qBqscC2BdE_sViIY
"""

def hi_my_name_is():
    return "Yi Liu"

import write_your_name as name_point

def test_hi_my_name_is():
    assert len(name_point.hi_my_name_is())  > 1

print(hi_my_name_is())

